spring:
  # 데이터베이스 커넥션과 관련된 데이터 소스 설정
  # Hikari CP를 사용해서 커넥션 풀 등을 스프링부트가 알아서 세팅해줌
  datasource:
    # 데이터베이스 접근 url
    # MVCC: 여러 명이 한번에 접근했을 때 좀 더 빨리 처리됨;MVCC=TRUE
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # jpa 설정
  # 스프링부트 메뉴얼에서 설정법 확인 가능
  jpa:
    hibernate:
      # create: 애플리케이션 실행 시점에 테이블을 지우고 다시 생성
      # none: 데이터베이스의 정보가 유지됨
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true, System.out에 출력
        format_sql: true
        # default_batch_fetch_size: in query의 개수
        default_batch_fetch_size: 100

# 로깅 설정
logging:
  # 로그 레벨 설정
  level:
    # debug 모드 시 hibernate가 남기는 모든 sql을 볼 수 있음
    # 로거를 통해 출력
    org.hibernate.SQL: debug
    # 쿼리 파라미터 로그 남기기
    org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6